include: package:lint/strict.yaml

linter:
  rules:
    # avoid_classes_with_only_static_members: false
    # sort_constructors_first: true

    # Choose wisely, but you don't have to
    # prefer_double_quotes: true
    # prefer_single_quotes: true