name: batonchess
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=2.18.5 <3.0.0'

dependencies:
  another_xlider: ^1.1.2
  bloc: ^8.1.0
  bottom_nav_layout: ^3.0.9
  chess: ^0.7.0
  cupertino_icons: ^1.0.2
  dropdown_button2: ^1.9.4
  flex_color_scheme: ^6.1.2
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.1
  flutter_spinkit: ^5.1.0
  flutter_stateless_chessboard: ^0.0.2
  group_button: ^5.2.2
  http: ^0.13.5
  http_status_code: ^0.0.2
  intl: ^0.18.0
  meta: ^1.8.0
  shared_preferences: ^2.0.15
  text_scroll: ^0.1.2
  toggle_switch: ^2.0.1

dev_dependencies:
  flutter_launcher_icons: "^0.12.0"
  lint: ^2.0.0

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/batonchess.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  web:
    generate: true
    image_path: "assets/icon/batonchess.png"
    background_color: "#ffffff"
    theme_color: "#ffffff"
  windows:
    generate: true
    image_path: "assets/icon/batonchess.png"
    icon_size: 48
  linux:
    generate: true
    image_path: "assets/icon/batonchess.png"
  macos:
    generate: true
    image_path: "assets/icon/batonchess.png"

flutter:
  uses-material-design: true